name: edgex-device-camera
base: core20
license: Apache-2.0
adopt-info: metadata

architectures:
  - build-on: amd64
  - build-on: arm64

grade: stable
confinement: strict

# delhi: 0, edinburgh: 1, fuji: 2, geneva/hanoi: 3, ireland: 4
epoch: 4

slots:
  edgex-secretstore-token:
    interface: content
    content: edgex-secretstore-token
    source:
      write: [$SNAP_DATA/device-camera]

apps:
  device-camera:
    adapter: full
    command: bin/device-camera $CONFIG_PRO_ARG $CONF_ARG $REGISTRY_ARG
    command-chain:
      - bin/source-env-file.sh
    environment:
      CONFIG_PRO_ARG: "--cp=consul.http://localhost:8500"
      CONF_ARG: "--confdir=$SNAP_DATA/config/device-camera/res"
      REGISTRY_ARG: "--registry"
      DEVICE_PROFILESDIR: "$SNAP_DATA/config/device-camera/res/profiles"
      DEVICE_DEVICESDIR: "$SNAP_DATA/config/device-camera/res/devices"
      SECRETSTORE_TOKENFILE: $SNAP_DATA/device-camera/secrets-token.json
    daemon: simple
    install-mode: disable
    plugs: [network, network-bind]

plugs:
  device-config:
    interface: content 
    target: $SNAP_DATA/config/device-camera

parts:      
  helper-go:
    source: snap/local/helper-go
    plugin: make
    build-snaps:
      - go/1.18/stable
    override-build: |
      cd $SNAPCRAFT_PART_SRC
      make build
      install -DT ./helper-go $SNAPCRAFT_PART_INSTALL/bin/helper-go

  device-camera:
    after: [metadata]
    source: .
    plugin: make
    build-packages: [git, libzmq3-dev, pkg-config]
    stage-packages: [libzmq5]
    build-snaps:
      - go/1.18/stable
    override-build: |
      cd $SNAPCRAFT_PART_SRC

      # the version is needed for the build
      cat ./VERSION

      go mod tidy
      make build

      install -DT "./cmd/device-camera" "$SNAPCRAFT_PART_INSTALL/bin/device-camera"

      RES=$SNAPCRAFT_PART_INSTALL/config/device-camera/res/
      mkdir -p $RES
      cp    cmd/res/configuration.toml $RES

      cp -r cmd/res/profiles $RES
      
      DOC=$SNAPCRAFT_PART_INSTALL/usr/share/doc/device-camera
      mkdir -p $DOC
      cp Attribution.txt $DOC/Attribution.txt
      cp LICENSE $DOC/LICENSE

  local-bin:
    plugin: dump
    source: snap/local/bin
    organize:
      source-env-file.sh: bin/source-env-file.sh

  metadata:
    plugin: nil
    source: https://github.com/canonical/edgex-snap-metadata.git
    source-branch: appstream
    source-depth: 1
    override-build: |
      # install the icon at the default internal path
      install -DT edgex-snap-icon.png \
        $SNAPCRAFT_PART_INSTALL/meta/gui/icon.png
      
      # change to this project's repo to get the version
      cd $SNAPCRAFT_PROJECT_DIR
      if git describe ; then
        VERSION=$(git describe --tags --abbrev=0 | sed 's/v//')
      else
        VERSION="0.0.0"
      fi
      
      # write version to file for the build
      echo $VERSION > ./VERSION
      # set the version of this snap
      snapcraftctl set-version $VERSION
    parse-info: [edgex-device-camera.metainfo.xml]
